package tmux

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/mieubrisse/stacktrace"
)

// agencKeyTable is the tmux key table name used to namespace all AgenC
// keybindings behind a prefix (prefix + a → agenc table).
const agencKeyTable = "agenc"

// GenerateKeybindingsContent returns the full content of the agenc-managed
// tmux keybindings configuration file. The tmuxMajor/tmuxMinor parameters
// control version-gated features (e.g. display-popup requires tmux >= 3.2).
// The agencBinary parameter is the binary name or path used in run-shell
// commands (e.g. "agenc" or "/usr/local/bin/agenc-dev").
func GenerateKeybindingsContent(tmuxMajor, tmuxMinor int, agencBinary string) string {
	var sb strings.Builder

	sb.WriteString("# AgenC tmux keybindings\n")
	sb.WriteString("# Generated by: agenc tmux inject\n")
	sb.WriteString("# Do not edit — this file is overwritten on each run.\n")
	sb.WriteString("\n")

	// prefix + a enters the agenc key table
	sb.WriteString("# Enter the AgenC key table (prefix + a)\n")
	fmt.Fprintf(&sb, "bind-key a switch-client -T %s\n", agencKeyTable)
	sb.WriteString("\n")

	// agenc table: n — new mission in a new window
	sb.WriteString("# New mission in a new window (prefix + a, n)\n")
	fmt.Fprintf(&sb, "bind-key -T %s n run-shell '%s tmux window new -- %s mission new'\n", agencKeyTable, agencBinary, agencBinary)

	sb.WriteString("\n")

	// agenc table: p — new mission in a side-by-side pane
	sb.WriteString("# New mission in a side-by-side pane (prefix + a, p)\n")
	fmt.Fprintf(&sb, "bind-key -T %s p run-shell '%s tmux pane new -- %s mission new'\n", agencKeyTable, agencBinary, agencBinary)

	sb.WriteString("\n")

	// Natural language 'do' command (prefix + a, d)
	sb.WriteString("# Natural language do command (prefix + a, d)\n")
	fmt.Fprintf(&sb, "bind-key -T %s d run-shell '%s tmux window new -- %s do'\n", agencKeyTable, agencBinary, agencBinary)

	// Command palette (requires tmux >= 3.2 for display-popup)
	if tmuxMajor > 3 || (tmuxMajor == 3 && tmuxMinor >= 2) {
		sb.WriteString("\n")
		sb.WriteString("# Command palette (prefix + a, k)\n")
		fmt.Fprintf(&sb, "bind-key -T %s k run-shell 'tmux display-popup -E -w 60%% -h 50%% \"%s tmux palette\"'\n", agencKeyTable, agencBinary)
	}

	return sb.String()
}

// WriteKeybindingsFile writes the agenc-managed keybindings file, overwriting
// any previous version. The tmuxMajor/tmuxMinor parameters control
// version-gated keybindings. The agencBinary parameter is the binary name or
// path used in run-shell commands.
func WriteKeybindingsFile(keybindingsFilepath string, tmuxMajor, tmuxMinor int, agencBinary string) error {
	content := GenerateKeybindingsContent(tmuxMajor, tmuxMinor, agencBinary)
	if err := os.WriteFile(keybindingsFilepath, []byte(content), 0644); err != nil {
		return stacktrace.Propagate(err, "failed to write keybindings file '%s'", keybindingsFilepath)
	}
	return nil
}

// SourceKeybindings sources the keybindings file into a running tmux server.
// Returns silently if no tmux server is running.
func SourceKeybindings(keybindingsFilepath string) error {
	// Check if tmux server is running
	if err := exec.Command("tmux", "list-sessions").Run(); err != nil {
		return nil
	}

	if err := exec.Command("tmux", "source-file", keybindingsFilepath).Run(); err != nil {
		return stacktrace.Propagate(err, "failed to source keybindings into running tmux server")
	}

	return nil
}
