package config

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"syscall"
	"unicode"

	"github.com/goccy/go-yaml"
	"github.com/mieubrisse/stacktrace"

	"github.com/odyssey/agenc/internal/launchd"
	"github.com/odyssey/agenc/internal/sleep"
)

// canonicalRepoRegex matches the canonical repo format: github.com/owner/repo
var canonicalRepoRegex = regexp.MustCompile(`^github\.com/[^/]+/[^/]+$`)

// CronConfig represents the configuration for a single cron job.
type CronConfig struct {
	ID          string `yaml:"id,omitempty"`          // UUID, auto-generated by cron new
	Schedule    string `yaml:"schedule"`              // Cron expression (5 or 6 fields)
	Prompt      string `yaml:"prompt"`                // Initial prompt for the mission
	Description string `yaml:"description,omitempty"` // Human-readable description
	Repo        string `yaml:"repo,omitempty"`        // Git repo to clone into workspace
	Enabled     *bool  `yaml:"enabled,omitempty"`     // Defaults to true if omitted
}

// IsEnabled returns whether the cron job is enabled. Defaults to true if not explicitly set.
func (c *CronConfig) IsEnabled() bool {
	if c.Enabled == nil {
		return true
	}
	return *c.Enabled
}

// StringPtr returns a pointer to the given string. It is a convenience helper
// for constructing PaletteCommandConfig literals with *string fields.
func StringPtr(s string) *string {
	return &s
}

// derefStr returns the string value of a *string, or "" if nil.
func derefStr(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

// PaletteCommandConfig represents a palette command entry in config.yml.
// For custom commands, all fields are user-provided.
// For builtin overrides, non-nil fields override the builtin defaults.
// A nil pointer means "not set" (inherit the builtin default), while a pointer
// to an empty string means "explicitly cleared."
// Set Disabled to true to hide a command from the palette entirely.
type PaletteCommandConfig struct {
	Title          *string `yaml:"title,omitempty"`
	Description    *string `yaml:"description,omitempty"`
	Command        *string `yaml:"command,omitempty"`
	TmuxKeybinding *string `yaml:"tmuxKeybinding,omitempty"`
	Disabled       bool    `yaml:"disabled,omitempty"`
}

// IsEmpty returns true if the entry carries no meaningful information —
// all pointer fields are nil and the command is not disabled. An empty
// builtin override can safely be removed from config (it has no effect).
func (c *PaletteCommandConfig) IsEmpty() bool {
	return !c.Disabled && c.Title == nil && c.Description == nil && c.Command == nil && c.TmuxKeybinding == nil
}

// BuiltinPaletteCommands defines the default palette commands shipped with agenc.
// Keys match the config.yml paletteCommands keys for override/disable purposes.
// Commands are self-contained strings that include their own tmux primitives
// (display-popup, split-window, new-window) when needed.
var BuiltinPaletteCommands = map[string]PaletteCommandConfig{
	"quickClaude": {
		Title:       StringPtr("🦀  Quick Claude"),
		Description: StringPtr("Creates a blank mission in a new window"),
		Command:     StringPtr("agenc mission new --blank"),
	},
	"talkToAgenc": {
		Title:       StringPtr("🤖  Adjutant"),
		Description: StringPtr("Launch an Adjutant mission in a new window"),
		Command:     StringPtr("agenc mission new --adjutant"),
	},
	"showNotifications": {
		Title:       StringPtr("🔔  Show Notifications"),
		Description: StringPtr("Review unread AgenC notifications via Adjutant"),
		Command:     StringPtr(`agenc mission new --adjutant --prompt "The user opened the Show Notifications palette entry. Run 'agenc notifications ls', read the unread notifications, summarize them concisely, and ask the user how they'd like to proceed. For any writeable_copy.* notifications, follow the guidance in the Notifications section of your prompt to help the user resolve them."`),
	},
	"newMission": {
		Title:          StringPtr("🚀  New Mission"),
		Description:    StringPtr("Create a new mission and launch Claude"),
		Command:        StringPtr(`tmux display-popup -E -w 68% -h 63% "agenc mission new"`),
		TmuxKeybinding: StringPtr("-n C-n"),
	},
	"switchMission": {
		Title:          StringPtr("🔀  Attach Mission"),
		Description:    StringPtr("Attach a mission to this tmux session (auto-resumes stopped/archived missions)"),
		Command:        StringPtr(`tmux display-popup -E -w 85% -h 80% "agenc mission attach"`),
		TmuxKeybinding: StringPtr("-n C-m"),
	},
	"detachMission": {
		Title:          StringPtr("🔌  Detach Mission"),
		Description:    StringPtr("Unlink the focused mission from this tmux session (keeps running)"),
		Command:        StringPtr("agenc mission detach $AGENC_CALLING_MISSION_UUID"),
		TmuxKeybinding: StringPtr("-n C-i"),
	},
	"sideShell": {
		Title:          StringPtr("🐚  Side Shell"),
		Description:    StringPtr("Split pane and open a shell in the current mission's workspace"),
		Command:        StringPtr(`tmux split-window -h -c "${AGENC_DIRPATH:-$HOME/.agenc}/missions/$AGENC_CALLING_MISSION_UUID/agent" $SHELL`),
		TmuxKeybinding: StringPtr("-n C-p"),
	},
	"draft": {
		Title:          StringPtr("📝  Side Draft"),
		Description:    StringPtr("Draft text in a side editor and paste it into the mission's pane"),
		Command:        StringPtr(`tmux split-window -h "agenc mission draft $AGENC_CALLING_MISSION_UUID"`),
		TmuxKeybinding: StringPtr("-n C-'"),
	},
	"shell": {
		Title:       StringPtr("🐚  Shell"),
		Description: StringPtr("Open a shell in a new window"),
		Command:     StringPtr(`tmux new-window -a -c "${AGENC_DIRPATH:-$HOME/.agenc}/missions/$AGENC_CALLING_MISSION_UUID/agent" $SHELL`),
	},
	"copyMissionUuid": {
		Title:       StringPtr("📋  Copy Mission ID"),
		Description: StringPtr("Copy the focused mission's UUID to the clipboard"),
		Command:     StringPtr(`printf '%s' $AGENC_CALLING_MISSION_UUID | pbcopy`),
	},
	"renameSession": {
		Title:          StringPtr("✨  Rename Session"),
		Description:    StringPtr("Rename the focused mission's window"),
		Command:        StringPtr(`tmux display-popup -E -w 68% -h 63% "agenc mission rename $AGENC_CALLING_MISSION_UUID"`),
		TmuxKeybinding: StringPtr("-n C-."),
	},
	"stopMission": {
		Title:       StringPtr("🛑  Stop Mission"),
		Description: StringPtr("Stop the mission in the focused pane"),
		Command:     StringPtr("agenc mission stop $AGENC_CALLING_MISSION_UUID"),
	},
	"rebuildContainer": {
		Title:       StringPtr("🐳  Rebuild Container"),
		Description: StringPtr("Rebuild the devcontainer and restart Claude"),
		Command:     StringPtr("agenc mission rebuild $AGENC_CALLING_MISSION_UUID"),
	},
	"reloadMission": {
		Title:       StringPtr("🔄  Reload Mission"),
		Description: StringPtr("Stop and restart the mission in the focused pane"),
		Command:     StringPtr("agenc mission reload $AGENC_CALLING_MISSION_UUID"),
	},
	"removeMission": {
		Title:       StringPtr("❌  Remove Mission"),
		Description: StringPtr("Remove a mission and its directory"),
		Command:     StringPtr(`tmux display-popup -E -w 68% -h 63% "agenc mission rm"`),
	},
	"nukeMissions": {
		Title:       StringPtr("💥  Nuke Missions"),
		Description: StringPtr("Remove all archived missions"),
		Command:     StringPtr(`tmux display-popup -E -w 68% -h 63% "agenc mission nuke"`),
	},
	"sendFeedback": {
		Title:       StringPtr("💬  Send Feedback"),
		Description: StringPtr("Send feedback about AgenC"),
		Command:     StringPtr(`agenc mission new --adjutant --prompt "I'd like to send feedback about AgenC"`),
	},
	"joinDiscord": {
		Title:       StringPtr("👾  Join the Discord"),
		Description: StringPtr("Join the AgenC Discord community"),
		Command:     StringPtr("agenc discord"),
	},
	"starAgenc": {
		Title:       StringPtr("⭐  Star AgenC on Github"),
		Description: StringPtr("Open the AgenC GitHub repo in your browser"),
		Command:     StringPtr("agenc star"),
	},
	"stashWorkspace": {
		Title:       StringPtr("📥  Stash Workspace"),
		Description: StringPtr("Stop all missions for later restore (useful for upgrading Claude)"),
		Command:     StringPtr(`tmux display-popup -E -w 68% -h 63% "agenc stash push"`),
	},
	"restoreWorkspace": {
		Title:       StringPtr("📤  Restore Workspace"),
		Description: StringPtr("Restore missions from a previously saved stash"),
		Command:     StringPtr(`tmux display-popup -E -w 68% -h 63% "agenc stash pop"`),
	},
	"exitTmux": {
		Title:       StringPtr("🚪  Exit"),
		Description: StringPtr("Detach from the session (missions keep running in the background)"),
		Command:     StringPtr("tmux detach"),
	},
}

// builtinPaletteCommandOrder controls the display order of builtin commands
// in the palette and ls output.
var builtinPaletteCommandOrder = []string{
	"quickClaude",
	"talkToAgenc",
	"showNotifications",
	"newMission",
	"switchMission",
	"detachMission",
	"sideShell",
	"draft",
	"shell",
	"copyMissionUuid",
	"renameSession",
	"stopMission",
	"rebuildContainer",
	"reloadMission",
	"removeMission",
	"nukeMissions",
	"stashWorkspace",
	"restoreWorkspace",
	"exitTmux",
	"sendFeedback",
	"joinDiscord",
	"starAgenc",
}

// BuiltinPaletteCommandOrder returns the display order of builtin commands.
func BuiltinPaletteCommandOrder() []string {
	result := make([]string, len(builtinPaletteCommandOrder))
	copy(result, builtinPaletteCommandOrder)
	return result
}

// CallingMissionUUIDEnvVar is the environment variable name that carries the
// focused mission's UUID into palette and keybinding commands.
const CallingMissionUUIDEnvVar = "AGENC_CALLING_MISSION_UUID"

// ResolvedPaletteCommand is a palette command with all defaults applied and
// the agenc binary substituted in the command string.
type ResolvedPaletteCommand struct {
	Name           string
	Title          string
	Description    string
	Command        string
	TmuxKeybinding string
	IsBuiltin      bool
}

// IsMissionScoped returns true if the command references the calling mission
// UUID environment variable, meaning it should only be available when a
// mission pane is focused.
func (c ResolvedPaletteCommand) IsMissionScoped() bool {
	return strings.Contains(c.Command, CallingMissionUUIDEnvVar)
}

// FormatKeybinding returns the human-readable keybinding string for this
// command (e.g. "prefix → a → d" for table-scoped keys, or "C-n" for root
// table keys), or an empty string if no keybinding is set.
func (c ResolvedPaletteCommand) FormatKeybinding() string {
	if c.TmuxKeybinding == "" {
		return ""
	}
	// Root table bindings (e.g. "-n C-p") should display without prefix
	if strings.HasPrefix(c.TmuxKeybinding, "-n ") {
		return strings.TrimPrefix(c.TmuxKeybinding, "-n ")
	}
	// Agenc table bindings (bare keys or "-T agenc x") use prefix
	return fmt.Sprintf("prefix → a → %s", c.TmuxKeybinding)
}

// DefaultPaletteTmuxKeybinding is the default bind-key arguments for the
// command palette keybinding. The value is inserted verbatim after "bind-key"
// in the generated tmux keybindings file, so it can include table specifiers
// (e.g. "-T agenc k") or bind directly on the prefix table (e.g. "C-k").
const DefaultPaletteTmuxKeybinding = "-n C-y"

// Default tmux window title coloring configuration.
const (
	DefaultTmuxWindowTitleBusyBg      = "colour018"
	DefaultTmuxWindowTitleBusyFg      = ""
	DefaultTmuxWindowTitleAttentionBg = "colour136"
	DefaultTmuxWindowTitleAttentionFg = ""
)

// Bounds for sessionTitleMaxWords. The lower bound matches the literal "3-"
// prefix baked into the summarizer system prompt, so values below 3 would
// render a nonsensical range. The upper cap prevents nonsense values that
// would no longer behave like a "title."
const (
	DefaultSessionTitleMaxWords = 15
	MinSessionTitleMaxWords     = 3
	MaxSessionTitleMaxWords     = 50
)

// TmuxWindowTitleConfig holds foreground and background color settings for
// the tmux window tab in busy and attention states. Empty strings disable
// coloring for that component.
type TmuxWindowTitleConfig struct {
	BusyBackgroundColor      *string `yaml:"busyBackgroundColor,omitempty"`
	BusyForegroundColor      *string `yaml:"busyForegroundColor,omitempty"`
	AttentionBackgroundColor *string `yaml:"attentionBackgroundColor,omitempty"`
	AttentionForegroundColor *string `yaml:"attentionForegroundColor,omitempty"`
}

// GetBusyBackgroundColor returns the busy background color, defaulting if not set.
func (t *TmuxWindowTitleConfig) GetBusyBackgroundColor() string {
	if t != nil && t.BusyBackgroundColor != nil {
		return *t.BusyBackgroundColor
	}
	return DefaultTmuxWindowTitleBusyBg
}

// GetBusyForegroundColor returns the busy foreground color, defaulting if not set.
func (t *TmuxWindowTitleConfig) GetBusyForegroundColor() string {
	if t != nil && t.BusyForegroundColor != nil {
		return *t.BusyForegroundColor
	}
	return DefaultTmuxWindowTitleBusyFg
}

// GetAttentionBackgroundColor returns the attention background color, defaulting if not set.
func (t *TmuxWindowTitleConfig) GetAttentionBackgroundColor() string {
	if t != nil && t.AttentionBackgroundColor != nil {
		return *t.AttentionBackgroundColor
	}
	return DefaultTmuxWindowTitleAttentionBg
}

// GetAttentionForegroundColor returns the attention foreground color, defaulting if not set.
func (t *TmuxWindowTitleConfig) GetAttentionForegroundColor() string {
	if t != nil && t.AttentionForegroundColor != nil {
		return *t.AttentionForegroundColor
	}
	return DefaultTmuxWindowTitleAttentionFg
}

// IsCanonicalRepoName reports whether the given string is in canonical format (github.com/owner/repo).
func IsCanonicalRepoName(name string) bool {
	return canonicalRepoRegex.MatchString(name)
}

// RepoConfig represents per-repo configuration in the repoConfig map.
// All fields are optional: alwaysSynced controls whether the server keeps
// the repo continuously fetched, emoji sets the display emoji for the repo,
// title sets a user-friendly display name, postUpdateHook specifies a shell
// command to run after repo updates, and writeableCopy designates a separate
// path the server keeps continuously synced with the same git remote
// (auto-commit local edits, pull-and-rebase remote changes). Setting
// writeableCopy implies alwaysSynced=true.
type RepoConfig struct {
	AlwaysSynced      bool               `yaml:"alwaysSynced,omitempty"`
	Emoji             string             `yaml:"emoji,omitempty"`
	Title             string             `yaml:"title,omitempty"`
	TrustedMcpServers *TrustedMcpServers `yaml:"trustedMcpServers,omitempty"`
	DefaultModel      string             `yaml:"defaultModel,omitempty"`
	PostUpdateHook    string             `yaml:"postUpdateHook,omitempty"`
	ClaudeArgs        []string           `yaml:"claudeArgs,omitempty"`
	WriteableCopy     string             `yaml:"writeableCopy,omitempty"`
}

// TrustedMcpServers configures MCP server trust for a repository.
// Supports two formats: "all" (trust every server in .mcp.json) or
// a list of named servers to trust.
type TrustedMcpServers struct {
	All  bool     // true when "all" is specified
	List []string // populated when a list of server names is specified
}

// UnmarshalYAML implements yaml.Unmarshaler to handle "all" (string)
// or a list of server names.
func (t *TrustedMcpServers) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var str string
	if err := unmarshal(&str); err == nil {
		if str == "all" {
			t.All = true
			return nil
		}
		return fmt.Errorf("trustedMcpServers: invalid value %q; must be \"all\" or a list of server names", str)
	}

	var list []string
	if err := unmarshal(&list); err == nil {
		if len(list) == 0 {
			return fmt.Errorf("trustedMcpServers: empty list is not valid; use \"all\" to trust all servers, or list at least one server name")
		}
		t.List = list
		return nil
	}

	return fmt.Errorf("trustedMcpServers: must be \"all\" or a list of server names")
}

// MarshalYAML implements yaml.InterfaceMarshaler to serialize back to
// either the string "all" or a list of server names.
func (t TrustedMcpServers) MarshalYAML() (interface{}, error) {
	if t.All {
		return "all", nil
	}
	return t.List, nil
}

// SleepModeConfig defines time windows during which mission and cron creation is blocked.
type SleepModeConfig struct {
	Windows []sleep.WindowDef `yaml:"windows"`
}

// AgencConfig represents the contents of config.yml.
type AgencConfig struct {
	RepoConfigs           map[string]RepoConfig           `yaml:"repoConfig,omitempty"`
	Crons                 map[string]CronConfig           `yaml:"crons,omitempty"`
	PaletteCommands       map[string]PaletteCommandConfig `yaml:"paletteCommands,omitempty"`
	PaletteTmuxKeybinding string                          `yaml:"paletteTmuxKeybinding,omitempty"`
	TmuxWindowTitle       *TmuxWindowTitleConfig          `yaml:"tmuxWindowTitle,omitempty"`
	DefaultModel          string                          `yaml:"defaultModel,omitempty"`
	ClaudeArgs            []string                        `yaml:"claudeArgs,omitempty"`
	SleepMode             *SleepModeConfig                `yaml:"sleepMode,omitempty"`
	SessionTitleMaxWords  int                             `yaml:"sessionTitleMaxWords,omitempty"`
}

// GetPaletteTmuxKeybinding returns the tmux key for the command palette,
// defaulting to "k" when not configured.
func (c *AgencConfig) GetPaletteTmuxKeybinding() string {
	if c.PaletteTmuxKeybinding == "" {
		return DefaultPaletteTmuxKeybinding
	}
	return c.PaletteTmuxKeybinding
}

// GetTmuxWindowTitleConfig returns the TmuxWindowTitleConfig, returning an
// empty config (which will use defaults) if the key is not set.
func (c *AgencConfig) GetTmuxWindowTitleConfig() *TmuxWindowTitleConfig {
	if c.TmuxWindowTitle != nil {
		return c.TmuxWindowTitle
	}
	return &TmuxWindowTitleConfig{}
}

// GetSessionTitleMaxWords returns the configured upper bound for words in the
// auto-generated session title. Zero means "unset" — defaults to
// DefaultSessionTitleMaxWords.
func (c *AgencConfig) GetSessionTitleMaxWords() int {
	if c.SessionTitleMaxWords == 0 {
		return DefaultSessionTitleMaxWords
	}
	return c.SessionTitleMaxWords
}

// GetAllSyncedRepos returns the sorted list of repo names that have alwaysSynced enabled.
func (c *AgencConfig) GetAllSyncedRepos() []string {
	var repos []string
	for repoName, rc := range c.RepoConfigs {
		if rc.AlwaysSynced {
			repos = append(repos, repoName)
		}
	}
	sort.Strings(repos)
	return repos
}

// GetWriteableCopy returns the writeable-copy path for a repo and whether one
// is configured.
func (c *AgencConfig) GetWriteableCopy(repoName string) (string, bool) {
	if rc, ok := c.RepoConfigs[repoName]; ok && rc.WriteableCopy != "" {
		return rc.WriteableCopy, true
	}
	return "", false
}

// GetAllWriteableCopies returns a map of repo name → writeable-copy path for
// every repo with one configured.
func (c *AgencConfig) GetAllWriteableCopies() map[string]string {
	out := make(map[string]string)
	for name, rc := range c.RepoConfigs {
		if rc.WriteableCopy != "" {
			out[name] = rc.WriteableCopy
		}
	}
	return out
}

// NormalizeRepoConfigs enforces invariants on RepoConfig entries. Currently:
// any repo with a non-empty WriteableCopy must have AlwaysSynced=true, since
// writeable copies require the repo library to be continuously fresh as a
// fan-out trigger.
func (c *AgencConfig) NormalizeRepoConfigs() {
	for name, rc := range c.RepoConfigs {
		if rc.WriteableCopy != "" && !rc.AlwaysSynced {
			rc.AlwaysSynced = true
			c.RepoConfigs[name] = rc
		}
	}
}

// GetRepoEmoji returns the configured emoji for a repo, or empty string if none is set.
func (c *AgencConfig) GetRepoEmoji(repoName string) string {
	if rc, ok := c.RepoConfigs[repoName]; ok {
		return rc.Emoji
	}
	return ""
}

// GetRepoTitle returns the configured title for a repo, or empty string if none is set.
func (c *AgencConfig) GetRepoTitle(repoName string) string {
	if rc, ok := c.RepoConfigs[repoName]; ok {
		return rc.Title
	}
	return ""
}

// GetRepoConfig returns the config for a repo and whether it exists.
func (c *AgencConfig) GetRepoConfig(repoName string) (RepoConfig, bool) {
	rc, ok := c.RepoConfigs[repoName]
	return rc, ok
}

// SetRepoConfig sets or updates the config for a repo.
func (c *AgencConfig) SetRepoConfig(repoName string, rc RepoConfig) {
	if c.RepoConfigs == nil {
		c.RepoConfigs = make(map[string]RepoConfig)
	}
	c.RepoConfigs[repoName] = rc
}

// RemoveRepoConfig removes the config entry for a repo.
// Returns true if the entry existed and was removed.
func (c *AgencConfig) RemoveRepoConfig(repoName string) bool {
	if _, ok := c.RepoConfigs[repoName]; !ok {
		return false
	}
	delete(c.RepoConfigs, repoName)
	return true
}

// IsAlwaysSynced reports whether the given repo has alwaysSynced enabled.
func (c *AgencConfig) IsAlwaysSynced(repoName string) bool {
	if rc, ok := c.RepoConfigs[repoName]; ok {
		return rc.AlwaysSynced
	}
	return false
}

// SetAlwaysSynced sets the alwaysSynced flag for a repo, creating the entry if needed.
func (c *AgencConfig) SetAlwaysSynced(repoName string, synced bool) {
	if c.RepoConfigs == nil {
		c.RepoConfigs = make(map[string]RepoConfig)
	}
	rc := c.RepoConfigs[repoName]
	rc.AlwaysSynced = synced
	c.RepoConfigs[repoName] = rc
}

// GetDefaultModel returns the resolved model for a given repo.
// Precedence: repoConfig.defaultModel > config.defaultModel > "" (Claude decides).
func (c *AgencConfig) GetDefaultModel(repoName string) string {
	if repoName != "" {
		if rc, ok := c.RepoConfigs[repoName]; ok && rc.DefaultModel != "" {
			return rc.DefaultModel
		}
	}
	return c.DefaultModel
}

// GetClaudeArgs returns the merged Claude CLI args for a given repo.
// Precedence: global claudeArgs first, then per-repo claudeArgs appended.
func (c *AgencConfig) GetClaudeArgs(repoName string) []string {
	var result []string
	result = append(result, c.ClaudeArgs...)
	if repoName != "" {
		if rc, ok := c.RepoConfigs[repoName]; ok {
			result = append(result, rc.ClaudeArgs...)
		}
	}
	return result
}

// GetConfigFilepath returns the path to config.yml inside the config directory.
func GetConfigFilepath(agencDirpath string) string {
	return filepath.Join(agencDirpath, ConfigDirname, ConfigFilename)
}

// AcquireConfigLock acquires an advisory file lock on config.yml.lock to
// prevent concurrent read-modify-write races across CLI processes.
// Returns a release function that must be called (typically via defer) when
// the caller is done with the config. The lock file is created if it does
// not exist.
func AcquireConfigLock(agencDirpath string) (func(), error) {
	lockFilepath := GetConfigFilepath(agencDirpath) + ".lock"
	f, err := os.OpenFile(lockFilepath, os.O_CREATE|os.O_RDWR, 0644)
	if err != nil {
		return nil, stacktrace.Propagate(err, "failed to open config lock file")
	}

	fd := int(f.Fd()) //nolint:gosec // file descriptor fits in int on all supported platforms
	if err := syscall.Flock(fd, syscall.LOCK_EX); err != nil {
		f.Close()
		return nil, stacktrace.Propagate(err, "failed to acquire config lock")
	}

	release := func() {
		_ = syscall.Flock(fd, syscall.LOCK_UN)
		f.Close()
	}
	return release, nil
}

// ReadAgencConfig reads and parses config.yml. Returns an empty config if the
// file does not exist. Returns an error if any repoConfig key is not in
// canonical format (github.com/owner/repo).
// The returned yaml.CommentMap captures any YAML comments for round-trip
// preservation; callers that only read config may discard it with _.
func ReadAgencConfig(agencDirpath string) (*AgencConfig, yaml.CommentMap, error) {
	configFilepath := GetConfigFilepath(agencDirpath)

	data, err := os.ReadFile(configFilepath)
	if err != nil {
		if os.IsNotExist(err) {
			return &AgencConfig{}, nil, nil
		}
		return nil, nil, stacktrace.Propagate(err, "failed to read config file '%s'", configFilepath)
	}

	var cfg AgencConfig
	cm := yaml.CommentMap{}
	if err := yaml.UnmarshalWithOptions(data, &cfg, yaml.CommentToMap(cm)); err != nil {
		return nil, nil, stacktrace.Propagate(err, "failed to parse config file '%s'", configFilepath)
	}

	if err := validateRepoConfigs(&cfg, configFilepath); err != nil {
		return nil, nil, err
	}

	if err := validateCronConfigs(&cfg, configFilepath); err != nil {
		return nil, nil, err
	}

	if err := validatePaletteCommandConfigs(&cfg, configFilepath); err != nil {
		return nil, nil, err
	}

	// Validate uniqueness of titles and keybindings across the resolved set
	if err := validatePaletteUniqueness(&cfg, configFilepath); err != nil {
		return nil, nil, err
	}

	if err := validateSleepMode(&cfg); err != nil {
		return nil, nil, err
	}

	// Validate and populate defaults
	if err := ValidateAndPopulateDefaults(&cfg); err != nil {
		return nil, nil, stacktrace.Propagate(err, "validation failed for %s", configFilepath)
	}

	cfg.NormalizeRepoConfigs()

	return &cfg, cm, nil
}

// validateRepoConfigs initializes the RepoConfigs map if nil and validates that
// every key matches the canonical "github.com/owner/repo" format.
func validateRepoConfigs(cfg *AgencConfig, configFilepath string) error {
	if cfg.RepoConfigs == nil {
		cfg.RepoConfigs = make(map[string]RepoConfig)
	}
	for repoName := range cfg.RepoConfigs {
		if !canonicalRepoRegex.MatchString(repoName) {
			return stacktrace.NewError(
				"invalid repoConfig key '%s' in %s; must be in canonical format 'github.com/owner/repo'",
				repoName, configFilepath,
			)
		}
	}
	return nil
}

// validateCronConfigs initializes the Crons map if nil and validates each cron
// entry's name, schedule, prompt, repo, overlap policy, and timeout.
func validateCronConfigs(cfg *AgencConfig, configFilepath string) error {
	if cfg.Crons == nil {
		cfg.Crons = make(map[string]CronConfig)
	}
	for name, cronCfg := range cfg.Crons {
		if err := ValidateCronName(name); err != nil {
			return stacktrace.Propagate(err, "invalid cron name in %s", configFilepath)
		}
		if err := ValidateCronSchedule(cronCfg.Schedule); err != nil {
			return stacktrace.Propagate(err, "invalid schedule for cron '%s' in %s", name, configFilepath)
		}
		if cronCfg.Prompt == "" {
			return stacktrace.NewError("cron '%s' in %s must have a prompt", name, configFilepath)
		}
		if cronCfg.Repo != "" && !canonicalRepoRegex.MatchString(cronCfg.Repo) {
			return stacktrace.NewError(
				"invalid repo '%s' for cron '%s' in %s; must be in canonical format 'github.com/owner/repo'",
				cronCfg.Repo, name, configFilepath,
			)
		}
	}
	return nil
}

// validateSleepMode validates each window in the sleep mode configuration, if present.
func validateSleepMode(cfg *AgencConfig) error {
	if cfg.SleepMode == nil {
		return nil
	}
	for i, w := range cfg.SleepMode.Windows {
		if err := sleep.ValidateWindow(w); err != nil {
			return stacktrace.Propagate(err, "sleepMode.windows[%d]", i)
		}
	}
	return nil
}

// ValidateSessionTitleMaxWords returns an error if v is outside the supported
// range [MinSessionTitleMaxWords, MaxSessionTitleMaxWords]. Zero is rejected
// as out-of-range — the file-load path skips validation when the field is
// zero (treating it as "key absent from YAML"), but explicit user input via
// `config set 0` must error rather than silently become the default.
func ValidateSessionTitleMaxWords(v int) error {
	if v < MinSessionTitleMaxWords || v > MaxSessionTitleMaxWords {
		return stacktrace.NewError(
			"sessionTitleMaxWords must be between %d and %d, got %d",
			MinSessionTitleMaxWords, MaxSessionTitleMaxWords, v,
		)
	}
	return nil
}

// validatePaletteCommandConfigs initializes the PaletteCommands map if nil and
// validates each entry's name, and requires title and command for non-builtin,
// non-disabled entries that have content.
func validatePaletteCommandConfigs(cfg *AgencConfig, configFilepath string) error {
	if cfg.PaletteCommands == nil {
		cfg.PaletteCommands = make(map[string]PaletteCommandConfig)
	}
	for name, cmdCfg := range cfg.PaletteCommands {
		if err := ValidatePaletteCommandName(name); err != nil {
			return stacktrace.Propagate(err, "invalid palette command name in %s", configFilepath)
		}
		// Custom (non-builtin) entries with content must have title and command
		_, isBuiltin := BuiltinPaletteCommands[name]
		if !isBuiltin && !cmdCfg.IsEmpty() && !cmdCfg.Disabled {
			if cmdCfg.Title == nil || *cmdCfg.Title == "" {
				return stacktrace.NewError("palette command '%s' in %s must have a title", name, configFilepath)
			}
			if cmdCfg.Command == nil || *cmdCfg.Command == "" {
				return stacktrace.NewError("palette command '%s' in %s must have a command", name, configFilepath)
			}
		}
	}
	return nil
}

// WriteAgencConfig marshals and writes config.yml. Pass the yaml.CommentMap
// returned by ReadAgencConfig to preserve YAML comments through round-trips;
// pass nil if no comments need preserving.
func WriteAgencConfig(agencDirpath string, cfg *AgencConfig, cm yaml.CommentMap) error {
	configFilepath := GetConfigFilepath(agencDirpath)

	var (
		data []byte
		err  error
	)
	if cm != nil {
		data, err = yaml.MarshalWithOptions(cfg, yaml.WithComment(cm))
	} else {
		data, err = yaml.Marshal(cfg)
	}
	if err != nil {
		return stacktrace.Propagate(err, "failed to marshal config")
	}

	if err := os.WriteFile(configFilepath, data, 0644); err != nil {
		return stacktrace.Propagate(err, "failed to write config file '%s'", configFilepath)
	}

	return nil
}

// EnsureConfigFile creates config.yml with a minimal empty configuration if it
// does not already exist.
func EnsureConfigFile(agencDirpath string) error {
	configFilepath := GetConfigFilepath(agencDirpath)

	if _, err := os.Stat(configFilepath); err == nil {
		return nil
	}

	if err := os.WriteFile(configFilepath, []byte("{}\n"), 0644); err != nil {
		return stacktrace.Propagate(err, "failed to create config file '%s'", configFilepath)
	}

	return nil
}

// cronNameRegex matches valid cron names: alphanumeric, hyphens, underscores.
var cronNameRegex = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9_-]*$`)

// ValidatePaletteCommandName checks whether a palette command name is valid.
// Names follow the same rules as cron names: start with a letter,
// contain only letters, numbers, hyphens, and underscores, max 64 characters.
func ValidatePaletteCommandName(name string) error {
	if name == "" {
		return stacktrace.NewError("palette command name cannot be empty")
	}
	if len(name) > 64 {
		return stacktrace.NewError("palette command name too long (max 64 characters)")
	}
	if !cronNameRegex.MatchString(name) {
		return stacktrace.NewError("palette command name '%s' is invalid; must start with a letter and contain only letters, numbers, hyphens, and underscores", name)
	}
	return nil
}

// IsBuiltinPaletteCommand returns true if the name is a builtin palette command.
func IsBuiltinPaletteCommand(name string) bool {
	_, ok := BuiltinPaletteCommands[name]
	return ok
}

// GetResolvedPaletteCommands returns the fully merged list of palette commands:
// builtins (with user overrides applied) followed by custom entries (alphabetical).
// Disabled builtins (empty override) are excluded.
func (c *AgencConfig) GetResolvedPaletteCommands() []ResolvedPaletteCommand {
	var result []ResolvedPaletteCommand

	// Process builtins in defined order
	for _, name := range builtinPaletteCommandOrder {
		builtin := BuiltinPaletteCommands[name]
		override, hasOverride := c.PaletteCommands[name]

		if hasOverride && override.Disabled {
			// Explicitly disabled — skip entirely
			continue
		}

		resolved := ResolvedPaletteCommand{
			Name:           name,
			Title:          derefStr(builtin.Title),
			Description:    derefStr(builtin.Description),
			Command:        derefStr(builtin.Command),
			TmuxKeybinding: derefStr(builtin.TmuxKeybinding),
			IsBuiltin:      true,
		}

		// Apply overrides — non-nil fields replace defaults (including
		// pointer-to-empty-string, which explicitly clears the field).
		if hasOverride {
			if override.Title != nil {
				resolved.Title = *override.Title
			}
			if override.Description != nil {
				resolved.Description = *override.Description
			}
			if override.Command != nil {
				resolved.Command = *override.Command
			}
			if override.TmuxKeybinding != nil {
				resolved.TmuxKeybinding = *override.TmuxKeybinding
			}
		}

		result = append(result, resolved)
	}

	// Process custom entries (non-builtin keys) in alphabetical order
	customNames := make([]string, 0)
	for name := range c.PaletteCommands {
		if _, isBuiltin := BuiltinPaletteCommands[name]; !isBuiltin {
			customNames = append(customNames, name)
		}
	}
	sort.Strings(customNames)

	for _, name := range customNames {
		cmdCfg := c.PaletteCommands[name]
		if cmdCfg.IsEmpty() || cmdCfg.Disabled {
			continue
		}
		resolved := ResolvedPaletteCommand{
			Name:           name,
			Title:          derefStr(cmdCfg.Title),
			Description:    derefStr(cmdCfg.Description),
			Command:        derefStr(cmdCfg.Command),
			TmuxKeybinding: derefStr(cmdCfg.TmuxKeybinding),
			IsBuiltin:      false,
		}
		result = append(result, resolved)
	}

	return result
}

// validatePaletteUniqueness checks that titles and keybindings are unique across
// the resolved palette command set, and that the palette keybinding doesn't
// conflict with any command keybinding.
func validatePaletteUniqueness(cfg *AgencConfig, configFilepath string) error {
	resolved := cfg.GetResolvedPaletteCommands()
	paletteKey := cfg.GetPaletteTmuxKeybinding()

	seenTitles := make(map[string]string)      // title → command name
	seenKeybindings := make(map[string]string) // keybinding → command name

	for _, cmd := range resolved {
		if cmd.Title != "" {
			if existingName, ok := seenTitles[cmd.Title]; ok {
				return stacktrace.NewError(
					"duplicate palette title '%s' in %s: used by both '%s' and '%s'",
					cmd.Title, configFilepath, existingName, cmd.Name,
				)
			}
			seenTitles[cmd.Title] = cmd.Name
		}

		if cmd.TmuxKeybinding != "" {
			if existingName, ok := seenKeybindings[cmd.TmuxKeybinding]; ok {
				return stacktrace.NewError(
					"duplicate palette keybinding '%s' in %s: used by both '%s' and '%s'",
					cmd.TmuxKeybinding, configFilepath, existingName, cmd.Name,
				)
			}
			seenKeybindings[cmd.TmuxKeybinding] = cmd.Name
		}
	}

	// Check that the palette keybinding doesn't conflict with any command keybinding.
	// Command keybindings are bare keys within the agenc table, so a conflict is
	// only possible when the palette is also bound in the agenc table.
	if paletteAgencKey := extractAgencTableKey(paletteKey); paletteAgencKey != "" {
		if conflictName, ok := seenKeybindings[paletteAgencKey]; ok {
			return stacktrace.NewError(
				"palette keybinding '%s' conflicts with command '%s' in %s; set paletteTmuxKeybinding to a different key",
				paletteKey, conflictName, configFilepath,
			)
		}
	}

	return nil
}

// extractAgencTableKey returns the bare key from a palette keybinding string
// if it targets the agenc key table (e.g. "-T agenc k" → "k"). Returns ""
// if the keybinding is not in the agenc table.
func extractAgencTableKey(paletteKeybinding string) string {
	const prefix = "-T agenc "
	if strings.HasPrefix(paletteKeybinding, prefix) {
		return strings.TrimPrefix(paletteKeybinding, prefix)
	}
	return ""
}

// ValidateCronName checks whether a cron name is valid.
// Cron names must start with a letter and contain only letters, numbers, hyphens, and underscores.
func ValidateCronName(name string) error {
	if name == "" {
		return stacktrace.NewError("cron name cannot be empty")
	}
	if len(name) > 64 {
		return stacktrace.NewError("cron name too long (max 64 characters)")
	}
	if !cronNameRegex.MatchString(name) {
		return stacktrace.NewError("cron name '%s' is invalid; must start with a letter and contain only letters, numbers, hyphens, and underscores", name)
	}
	return nil
}

// ValidateCronSchedule checks whether a cron schedule expression is valid
// and compatible with macOS launchd's StartCalendarInterval. Only simple
// 5-field expressions with integer values or '*' are supported — no ranges,
// lists, step values, or named days/months.
func ValidateCronSchedule(schedule string) error {
	if schedule == "" {
		return stacktrace.NewError("cron schedule cannot be empty")
	}
	_, err := launchd.ParseCronExpression(schedule)
	if err != nil {
		return stacktrace.Propagate(err, "invalid cron schedule '%s'; AgenC uses macOS launchd which only supports simple values (e.g., '0 9 * * *', '0 0 * * 0')", schedule)
	}
	return nil
}

// ValidateGitRepoURL validates a git repository URL using full URL parsing.
// Accepts both HTTPS (https://github.com/owner/repo) and SSH (git@github.com:owner/repo) formats.
func ValidateGitRepoURL(repoURL string) error {
	if repoURL == "" {
		return stacktrace.NewError("git repo URL cannot be empty")
	}

	// Handle SSH format (git@github.com:owner/repo)
	if strings.HasPrefix(repoURL, "git@") {
		parts := strings.SplitN(repoURL, ":", 2)
		if len(parts) != 2 {
			return stacktrace.NewError("invalid SSH git URL '%s'; expected format 'git@host:owner/repo'", repoURL)
		}
		hostPart := parts[0]
		pathPart := parts[1]

		if !strings.Contains(hostPart, "@") || !strings.Contains(hostPart, ".") {
			return stacktrace.NewError("invalid SSH git URL host '%s'", hostPart)
		}

		if !strings.Contains(pathPart, "/") {
			return stacktrace.NewError("invalid SSH git URL path '%s'; expected 'owner/repo'", pathPart)
		}

		return nil
	}

	// Handle HTTPS format
	parsedURL, err := url.Parse(repoURL)
	if err != nil {
		return stacktrace.Propagate(err, "failed to parse git repo URL '%s'", repoURL)
	}

	if parsedURL.Scheme != "https" && parsedURL.Scheme != "http" {
		return stacktrace.NewError("git repo URL '%s' must use https:// or ssh (git@) scheme", repoURL)
	}

	if parsedURL.Host == "" {
		return stacktrace.NewError("git repo URL '%s' has no host", repoURL)
	}

	if parsedURL.Path == "" || parsedURL.Path == "/" {
		return stacktrace.NewError("git repo URL '%s' has no repository path", repoURL)
	}

	// Validate path structure for GitHub URLs
	if strings.Contains(parsedURL.Host, "github.com") {
		pathParts := strings.Split(strings.Trim(parsedURL.Path, "/"), "/")
		if len(pathParts) < 2 {
			return stacktrace.NewError("GitHub URL '%s' must have format 'https://github.com/owner/repo'", repoURL)
		}
	}

	return nil
}

// ValidatePathNoTraversal validates that a path does not contain traversal patterns.
// Rejects paths containing "../" or ".." as a path component.
func ValidatePathNoTraversal(path string) error {
	if path == "" {
		return nil
	}

	if strings.Contains(path, "..") {
		return stacktrace.NewError("path '%s' contains path traversal pattern '..'", path)
	}

	return nil
}

// SanitizePrompt removes control characters from user prompts.
// Returns the sanitized string and true if any characters were removed.
func SanitizePrompt(prompt string) (string, bool) {
	var sanitized strings.Builder
	modified := false

	for _, r := range prompt {
		// Allow printable characters, spaces, tabs, and newlines
		if unicode.IsPrint(r) || r == ' ' || r == '\t' || r == '\n' || r == '\r' {
			sanitized.WriteRune(r)
		} else {
			modified = true
		}
	}

	return sanitized.String(), modified
}

// ValidateAndPopulateDefaults validates all configuration values and applies defaults.
// This function should be called after reading config.yml to ensure all values are valid.
func ValidateAndPopulateDefaults(cfg *AgencConfig) error {
	// Validate cron configurations
	for name, cronCfg := range cfg.Crons {
		// Schedule and name are already validated by ReadAgencConfig

		// Validate and sanitize prompt
		if cronCfg.Prompt == "" {
			return stacktrace.NewError("cron '%s' prompt cannot be empty", name)
		}
		sanitized, modified := SanitizePrompt(cronCfg.Prompt)
		if modified {
			cronCfg.Prompt = sanitized
			cfg.Crons[name] = cronCfg
		}

		// Validate git repo URL if provided
		if cronCfg.Repo != "" {
			// Canonical format already validated, but also support full URLs
			if !canonicalRepoRegex.MatchString(cronCfg.Repo) {
				if err := ValidateGitRepoURL(cronCfg.Repo); err != nil {
					return stacktrace.Propagate(err, "invalid repo URL for cron '%s'", name)
				}
			}
		}

	}

	// Validate palette commands
	for name, cmdCfg := range cfg.PaletteCommands {
		// Name validation already done by ReadAgencConfig

		// Sanitize command string
		if cmdCfg.Command != nil && *cmdCfg.Command != "" {
			sanitized, modified := SanitizePrompt(*cmdCfg.Command)
			if modified {
				cmdCfg.Command = StringPtr(sanitized)
				cfg.PaletteCommands[name] = cmdCfg
			}
		}
	}

	// Zero on the file-load path means "key absent from YAML" (the field is
	// declared with omitempty, so a missing key and an explicit 0 are
	// indistinguishable after unmarshal). Skip validation for zero and let
	// GetSessionTitleMaxWords resolve it to the default. CLI `config set`
	// validates the user's input directly and rejects 0 there.
	if cfg.SessionTitleMaxWords != 0 {
		if err := ValidateSessionTitleMaxWords(cfg.SessionTitleMaxWords); err != nil {
			return err
		}
	}

	return nil
}
